-- The Library — database setup for Supabase
-- Run this whole file in Supabase's SQL editor once, and you're done.

-- Step 1: Create the books table
create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  author text not null,
  category text not null,
  created_at timestamptz default now()
);

-- Step 2: Enable Row Level Security with open-access policies
-- (fine for a personal app; tighten later if you ever want auth)
alter table public.books enable row level security;

drop policy if exists "public read" on public.books;
create policy "public read" on public.books for select using (true);

drop policy if exists "public insert" on public.books;
create policy "public insert" on public.books for insert with check (true);

drop policy if exists "public delete" on public.books;
create policy "public delete" on public.books for delete using (true);

drop policy if exists "public update" on public.books;
create policy "public update" on public.books for update using (true) with check (true);

-- Step 3: Clear any existing data (safe to re-run)
delete from public.books;

-- Step 4: Insert the catalogue
insert into public.books (title, author, category) values
  ('The Man from the Future: The Visionary Life of John von Neumann', 'Ananyo Bhattacharya', 'Science & Ideas'),
  ('How to Change Your Mind', 'Michael Pollan', 'Science & Ideas'),
  ('Freakonomics', 'Steven D. Levitt & Stephen J. Dubner', 'Business & Investing'),
  ('Risk Savvy', 'Gerd Gigerenzer', 'Business & Investing'),
  ('A History of the Bible', 'John Barton', 'History'),
  ('Napoleon the Great', 'Andrew Roberts', 'History'),
  ('Boomerang', 'Michael Lewis', 'Business & Investing'),
  ('Fooled by Randomness', 'Nassim Nicholas Taleb', 'Business & Investing'),
  ('The End', 'Ian Kershaw', 'History'),
  ('Civilization', 'Niall Ferguson', 'History'),
  ('Justice', 'Michael Sandel', 'Science & Ideas'),
  ('Winter King', 'Thomas Penn', 'History'),
  ('Evicted', 'Matthew Desmond', 'Narrative Non-Fiction'),
  ('A History of the World in 100 Objects', 'Neil MacGregor', 'History'),
  ('1599: A Year in the Life of William Shakespeare', 'James Shapiro', 'Literature & Reference'),
  ('Genghis Khan and the Making of the Modern World', 'Jack Weatherford', 'History'),
  ('The Spy and the Traitor', 'Ben Macintyre', 'Narrative Non-Fiction'),
  ('The Siege', 'Ben Macintyre', 'Narrative Non-Fiction'),
  ('Matterhorn', 'Karl Marlantes', 'Military History'),
  ('Factfulness', 'Hans Rosling', 'Science & Ideas'),
  ('One Night in Winter', 'Simon Sebag Montefiore', 'History'),
  ('Rebirding', 'Benedict Macdonald', 'Narrative Non-Fiction'),
  ('Dare to Do', 'Sarah Outen', 'Narrative Non-Fiction'),
  ('The Emperor of All Maladies', 'Siddhartha Mukherjee', 'Science & Ideas'),
  ('The Strange Death of Liberal England', 'George Dangerfield', 'History'),
  ('A Life Too Short: The Tragedy of Robert Enke', 'Ronald Reng', 'Biography & Memoir'),
  ('Deep', 'James Nestor', 'Narrative Non-Fiction'),
  ('This Is Your Mind on Plants', 'Michael Pollan', 'Science & Ideas'),
  ('The Secret Race', 'Tyler Hamilton & Daniel Coyle', 'Narrative Non-Fiction'),
  ('The Wager', 'David Grann', 'Narrative Non-Fiction'),
  ('Killers of the Flower Moon', 'David Grann', 'Narrative Non-Fiction'),
  ('How the Word Is Passed', 'Clint Smith', 'History'),
  ('The Ascent of Money', 'Niall Ferguson', 'Business & Investing'),
  ('Dark Emu', 'Bruce Pascoe', 'History'),
  ('Guns, Germs, and Steel', 'Jared Diamond', 'History'),
  ('Where Men Win Glory', 'Jon Krakauer', 'Narrative Non-Fiction'),
  ('How Democracies Die', 'Steven Levitsky & Daniel Ziblatt', 'Science & Ideas'),
  ('The Map That Changed the World', 'Simon Winchester', 'Science & Ideas'),
  ('Beyond Words', 'Carl Safina', 'Science & Ideas'),
  ('Golden Daze', 'Sean Doherty', 'Narrative Non-Fiction'),
  ('The Right Stuff', 'Tom Wolfe', 'Narrative Non-Fiction'),
  ('The Essential A.A. Gill: Far and Away', 'A.A. Gill', 'Literature & Reference'),
  ('A Good Walk Spoiled', 'John Feinstein', 'Narrative Non-Fiction'),
  ('Close to the Wind', 'Pete Goss', 'Biography & Memoir'),
  ('War Doctor', 'David Nott', 'Biography & Memoir'),
  ('No Fixed Abode', 'Maeve McClenaghan', 'Narrative Non-Fiction'),
  ('Enlightenment Now', 'Steven Pinker', 'Science & Ideas'),
  ('From Bacteria to Bach and Back', 'Daniel C. Dennett', 'Science & Ideas'),
  ('The End of Faith', 'Sam Harris', 'Science & Ideas'),
  ('Waking Up', 'Sam Harris', 'Science & Ideas'),
  ('Nothing', 'New Scientist (ed. Jeremy Webb)', 'Science & Ideas'),
  ('European Intellectual History from Rousseau to Nietzsche', 'Frank M. Turner', 'Science & Ideas'),
  ('Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 'Science & Ideas'),
  ('The Order of Time', 'Carlo Rovelli', 'Science & Ideas'),
  ('Homo Deus', 'Yuval Noah Harari', 'Science & Ideas'),
  ('The God Delusion', 'Richard Dawkins', 'Science & Ideas'),
  ('A Brief History of Time', 'Stephen Hawking', 'Science & Ideas'),
  ('Brief Answers to the Big Questions', 'Stephen Hawking', 'Science & Ideas'),
  ('Nudge', 'Richard H. Thaler & Cass R. Sunstein', 'Business & Investing'),
  ('Behave: The Biology of Humans at Our Best and Worst', 'Robert Sapolsky', 'Science & Ideas'),
  ('Atomic Habits', 'James Clear', 'Self-Development'),
  ('The United States of Paranoia', 'Jesse Walker', 'History'),
  ('Mindfulness', 'Mark Williams & Danny Penman', 'Self-Development'),
  ('Being Mortal', 'Atul Gawande', 'Science & Ideas'),
  ('Surely You''re Joking, Mr. Feynman!', 'Richard Feynman', 'Biography & Memoir'),
  ('E=mc²: A Biography of the World''s Most Famous Equation', 'David Bodanis', 'Science & Ideas'),
  ('Einstein''s Dreams', 'Alan Lightman', 'Fiction'),
  ('If This Is a Man / The Truce', 'Primo Levi', 'Biography & Memoir'),
  ('Man''s Search for Meaning', 'Viktor Frankl', 'Biography & Memoir'),
  ('The Denial of Death', 'Ernest Becker', 'Science & Ideas'),
  ('God Is Not Great', 'Christopher Hitchens', 'Science & Ideas'),
  ('Mortality', 'Christopher Hitchens', 'Biography & Memoir'),
  ('Arguably', 'Christopher Hitchens', 'Literature & Reference'),
  ('A History of the English-Speaking Peoples', 'Winston S. Churchill', 'Military History'),
  ('The Long Shadow', 'David Reynolds', 'Military History'),
  ('Going to the Wars', 'Max Hastings', 'Military History'),
  ('It Doesn''t Take a Hero', 'Norman Schwarzkopf & Peter Petre', 'Biography & Memoir'),
  ('The Korean War', 'Max Hastings', 'Military History'),
  ('Finest Years: Churchill as Warlord 1940-45', 'Max Hastings', 'Military History'),
  ('The Storm of War', 'Andrew Roberts', 'Military History'),
  ('Chastise', 'Max Hastings', 'Military History'),
  ('Return of a King', 'William Dalrymple', 'Military History'),
  ('The Proud Tower', 'Barbara Tuchman', 'History'),
  ('Soldiers', 'Max Hastings', 'Military History'),
  ('Vietnam', 'Max Hastings', 'Military History'),
  ('The Gulag Archipelago', 'Aleksandr Solzhenitsyn', 'History'),
  ('The Gulag Archipelago (second copy)', 'Aleksandr Solzhenitsyn', 'History'),
  ('An Impeccable Spy', 'Owen Matthews', 'Narrative Non-Fiction'),
  ('Killing Thatcher', 'Rory Carroll', 'History'),
  ('Crusaders', 'Dan Jones', 'History'),
  ('Henry V', 'Dan Jones', 'History'),
  ('Manhattan Project', 'Stéphane Groueff', 'Military History'),
  ('Ghost Empire', 'Richard Fidler', 'History'),
  ('1776', 'David McCullough', 'History'),
  ('The Battle for the Falklands', 'Max Hastings & Simon Jenkins', 'Military History'),
  ('Stalin: The Court of the Red Tsar', 'Simon Sebag Montefiore', 'History'),
  ('Dunkirk', 'Hugh Sebag-Montefiore', 'Military History'),
  ('The Price of Glory', 'Alistair Horne', 'Military History'),
  ('King Leopold''s Ghost', 'Adam Hochschild', 'History'),
  ('The Liberator: One World War II Soldier''s 500-Day Odyssey', 'Alex Kershaw', 'Military History'),
  ('Six Days of War', 'Michael B. Oren', 'Military History'),
  ('Unruly', 'David Mitchell', 'History'),
  ('Bloodlands: Europe Between Hitler and Stalin', 'Timothy Snyder', 'History'),
  ('Shah of Shahs', 'Ryszard Kapuściński', 'History'),
  ('Arnhem', 'Antony Beevor', 'Military History'),
  ('Justinian''s Flea', 'William Rosen', 'History'),
  ('The Anarchy', 'William Dalrymple', 'History'),
  ('The Golden Road', 'William Dalrymple', 'History'),
  ('The Secret War', 'Max Hastings', 'Military History'),
  ('A Rumor of War', 'Philip Caputo', 'Military History'),
  ('The Rise and Fall of the Third Reich', 'William L. Shirer', 'Military History'),
  ('Abyss', 'Max Hastings', 'Military History'),
  ('The Prize: The Epic Quest for Oil, Money & Power', 'Daniel Yergin', 'Business & Investing'),
  ('Catastrophe: Europe Goes to War 1914', 'Max Hastings', 'Military History'),
  ('The Origins of the Second World War', 'A.J.P. Taylor', 'Military History'),
  ('Endurance', 'Alfred Lansing', 'Narrative Non-Fiction'),
  ('A Bridge Too Far', 'Cornelius Ryan', 'Military History'),
  ('The Pursuit of Victory: The Life and Achievement of Horatio Nelson', 'Roger Knight', 'Biography & Memoir'),
  ('The War of the World: History''s Age of Hatred', 'Niall Ferguson', 'Military History'),
  ('Hellhound on His Trail', 'Hampton Sides', 'Narrative Non-Fiction'),
  ('1929: Inside the Greatest Crash in Wall Street History', 'Andrew Ross Sorkin', 'Business & Investing'),
  ('Against the Gods: The Remarkable Story of Risk', 'Peter L. Bernstein', 'Business & Investing'),
  ('The Chairman''s Lounge', 'Joe Aston', 'Business & Investing'),
  ('The Design of Business', 'Roger Martin', 'Business & Investing'),
  ('Shoe Dog', 'Phil Knight', 'Biography & Memoir'),
  ('The Ride of a Lifetime', 'Robert Iger', 'Biography & Memoir'),
  ('Economics: The User''s Guide', 'Ha-Joon Chang', 'Business & Investing'),
  ('The Billionaire Who Wasn''t', 'Conor O''Clery', 'Biography & Memoir'),
  ('Bad Blood', 'John Carreyrou', 'Business & Investing'),
  ('In Search of Excellence', 'Tom Peters & Robert Waterman', 'Business & Investing'),
  ('The Greatest Trade Ever', 'Gregory Zuckerman', 'Business & Investing'),
  ('Innovation and Entrepreneurship', 'Peter Drucker', 'Business & Investing'),
  ('Built to Last', 'Jim Collins & Jerry I. Porras', 'Business & Investing'),
  ('Barbarians at the Gate', 'Bryan Burrough & John Helyar', 'Business & Investing'),
  ('Barbarians at the Gate (second copy)', 'Bryan Burrough & John Helyar', 'Business & Investing'),
  ('High Output Management', 'Andrew S. Grove', 'Business & Investing'),
  ('The Key Man', 'Simon Clark & Will Louch', 'Business & Investing'),
  ('Money Men', 'Dan McCrum', 'Business & Investing'),
  ('Fall', 'John Preston', 'Biography & Memoir'),
  ('The Outsiders', 'William Thorndike', 'Business & Investing'),
  ('The Innovator''s Dilemma', 'Clayton Christensen', 'Business & Investing'),
  ('Principles', 'Ray Dalio', 'Business & Investing'),
  ('Narconomics', 'Tom Wainwright', 'Business & Investing'),
  ('The Culture Code', 'Daniel Coyle', 'Business & Investing'),
  ('Capital Ideas', 'Peter L. Bernstein', 'Business & Investing'),
  ('7 Powers: The Foundations of Business Strategy', 'Hamilton Helmer', 'Business & Investing'),
  ('Accounts Demystified', 'Anthony Rice', 'Business & Investing'),
  ('Beyond Entrepreneurship 2.0', 'Jim Collins', 'Business & Investing'),
  ('The Entrepreneur''s Roadmap: From Concept to IPO', 'Various', 'Business & Investing'),
  ('Billion Dollar Whale', 'Tom Wright & Bradley Hope', 'Business & Investing'),
  ('One from Many', 'Dee Hock', 'Business & Investing'),
  ('23 Things They Don''t Tell You About Capitalism', 'Ha-Joon Chang', 'Business & Investing'),
  ('Superforecasting', 'Philip Tetlock & Dan Gardner', 'Business & Investing'),
  ('The Money Machine', 'Philip Coggan', 'Business & Investing'),
  ('Who Moved My Cheese?', 'Spencer Johnson', 'Self-Development'),
  ('The Most Important Thing', 'Howard Marks', 'Business & Investing'),
  ('Strategy Beyond the Hockey Stick', 'Chris Bradley et al.', 'Business & Investing'),
  ('Sam Walton: Made in America', 'Sam Walton', 'Biography & Memoir'),
  ('Good to Great', 'Jim Collins', 'Business & Investing'),
  ('Creativity, Inc.', 'Ed Catmull', 'Business & Investing'),
  ('The Success Equation', 'Michael Mauboussin', 'Business & Investing'),
  ('Antifragile', 'Nassim Nicholas Taleb', 'Science & Ideas'),
  ('Strategic Intuition', 'William Duggan', 'Business & Investing'),
  ('Mastering Alliance Strategy', 'James Bamford et al.', 'Business & Investing'),
  ('Capital Ideas Evolving', 'Peter L. Bernstein', 'Business & Investing'),
  ('The Intelligent Investor', 'Benjamin Graham', 'Business & Investing'),
  ('A Brief History of Equality', 'Thomas Piketty', 'Business & Investing'),
  ('Capital in the Twenty-First Century', 'Thomas Piketty', 'Business & Investing'),
  ('Against the Odds: An Autobiography', 'James Dyson', 'Biography & Memoir'),
  ('Poor Charlie''s Almanack', 'Charles T. Munger', 'Business & Investing'),
  ('Goode on Commercial Law', 'Ewan McKendrick (ed.)', 'Literature & Reference'),
  ('Outback', 'Thomas Keneally', 'Australia'),
  ('The Pye Book of Science', 'Various', 'Literature & Reference'),
  ('Australian Pub Crawl', 'Baglin & Austin', 'Australia'),
  ('Classic Convertibles', 'Murray Child', 'Literature & Reference'),
  ('Wattle', 'Various', 'Australia'),
  ('The Art of Van Gogh', 'Nathaniel Harris', 'Literature & Reference'),
  ('The Inner Game of Tennis', 'W. Timothy Gallwey', 'Self-Development'),
  ('Ikigai', 'Héctor García & Francesc Miralles', 'Self-Development'),
  ('Lost Connections', 'Johann Hari', 'Science & Ideas'),
  ('Chasing the Scream', 'Johann Hari', 'Narrative Non-Fiction'),
  ('When Breath Becomes Air', 'Paul Kalanithi', 'Biography & Memoir'),
  ('The Nvidia Way: Jensen Huang and the Making of a Tech Giant', 'Tae Kim', 'Business & Investing'),
  ('The Future', 'Al Gore', 'Science & Ideas'),
  ('Born to Run', 'Bruce Springsteen', 'Biography & Memoir'),
  ('Patriot', 'Alexei Navalny', 'Biography & Memoir'),
  ('Source Code', 'Bill Gates', 'Biography & Memoir'),
  ('An Unfinished Life: John F. Kennedy 1917–1963', 'Robert Dallek', 'Biography & Memoir'),
  ('Personal History', 'Katharine Graham', 'Biography & Memoir'),
  ('Scar Tissue', 'Anthony Kiedis', 'Biography & Memoir'),
  ('Grant', 'Ron Chernow', 'Biography & Memoir'),
  ('Tall Tales and Wee Stories', 'Billy Connolly', 'Biography & Memoir'),
  ('Open', 'Andre Agassi', 'Biography & Memoir'),
  ('Father, Son & Co.', 'Thomas J. Watson Jr. & Peter Petre', 'Biography & Memoir'),
  ('The Black Swan', 'Nassim Nicholas Taleb', 'Business & Investing'),
  ('Blood and Thunder: The Epic Story of Kit Carson', 'Hampton Sides', 'Narrative Non-Fiction'),
  ('Longitude', 'Dava Sobel', 'Narrative Non-Fiction'),
  ('Dispatches', 'Michael Herr', 'Military History'),
  ('On Tyranny', 'Timothy Snyder', 'Science & Ideas'),
  ('Into Thin Air', 'Jon Krakauer', 'Narrative Non-Fiction'),
  ('The Unexpected Professor', 'John Carey', 'Biography & Memoir'),
  ('East West Street', 'Philippe Sands', 'History'),
  ('The Sixth Extinction', 'Elizabeth Kolbert', 'Science & Ideas'),
  ('Empire of Pain', 'Patrick Radden Keefe', 'Narrative Non-Fiction'),
  ('The Devil in the White City', 'Erik Larson', 'Narrative Non-Fiction'),
  ('Bury My Heart at Wounded Knee', 'Dee Brown', 'History'),
  ('A.A. Gill is Here and There', 'A.A. Gill', 'Literature & Reference'),
  ('Mr Nice', 'Howard Marks', 'Biography & Memoir'),
  ('The Secret Barrister', 'The Secret Barrister', 'Biography & Memoir'),
  ('Cod: A Biography of the Fish That Changed the World', 'Mark Kurlansky', 'Narrative Non-Fiction'),
  ('The Autobiography of Malcolm X', 'Alex Haley', 'Biography & Memoir'),
  ('The Outsider', 'Frederick Forsyth', 'Biography & Memoir'),
  ('Spillover', 'David Quammen', 'Science & Ideas'),
  ('The River of Doubt: Theodore Roosevelt''s Darkest Journey', 'Candice Millard', 'Narrative Non-Fiction'),
  ('The Best of A.A. Gill', 'A.A. Gill', 'Literature & Reference'),
  ('Escobar: The Inside Story of Pablo Escobar', 'Roberto Escobar', 'Biography & Memoir'),
  ('Ghost Soldiers', 'Hampton Sides', 'Military History'),
  ('The Viking Heart', 'Arthur Herman', 'History'),
  ('A Voyage for Madmen', 'Peter Nichols', 'Narrative Non-Fiction'),
  ('Prisoners of Geography', 'Tim Marshall', 'Science & Ideas'),
  ('Oxygen', 'William Trubridge', 'Biography & Memoir'),
  ('This Divided Island', 'Samanth Subramanian', 'History'),
  ('The Things They Carried', 'Tim O''Brien', 'Fiction'),
  ('War and Peace', 'Leo Tolstoy', 'Fiction'),
  ('Crime and Punishment', 'Fyodor Dostoevsky', 'Fiction'),
  ('Heart of Darkness', 'Joseph Conrad', 'Fiction'),
  ('Pride and Prejudice', 'Jane Austen', 'Fiction'),
  ('Of the Social Contract and Other Political Writings', 'Jean-Jacques Rousseau', 'Science & Ideas'),
  ('The Log of a Cowboy', 'Andy Adams', 'Fiction'),
  ('Slaughterhouse-Five', 'Kurt Vonnegut', 'Fiction'),
  ('To Kill a Mockingbird', 'Harper Lee', 'Fiction'),
  ('Frankenstein', 'Mary Shelley', 'Fiction'),
  ('Hiroshima', 'John Hersey', 'History'),
  ('Memoirs of an Infantry Officer', 'Siegfried Sassoon', 'Biography & Memoir'),
  ('The Stranger', 'Albert Camus', 'Fiction'),
  ('Steppenwolf', 'Hermann Hesse', 'Fiction'),
  ('The Power and the Glory', 'Graham Greene', 'Fiction'),
  ('Collected Short Stories', 'W. Somerset Maugham', 'Fiction'),
  ('A Confederacy of Dunces', 'John Kennedy Toole', 'Fiction'),
  ('Love in the Time of Cholera', 'Gabriel García Márquez', 'Fiction'),
  ('Madame Bovary', 'Gustave Flaubert', 'Fiction'),
  ('Wuthering Heights', 'Emily Brontë', 'Fiction'),
  ('The Secret History', 'Donna Tartt', 'Fiction'),
  ('The Getting of Wisdom', 'Henry Handel Richardson', 'Fiction'),
  ('George Orwell Essays', 'George Orwell', 'Literature & Reference'),
  ('Kingdom of Fear', 'Hunter S. Thompson', 'Biography & Memoir'),
  ('The Adventures of Tom Sawyer', 'Mark Twain', 'Fiction'),
  ('The Shadow of the Sun', 'Ryszard Kapuściński', 'Narrative Non-Fiction'),
  ('The Prince', 'Niccolò Machiavelli', 'Science & Ideas'),
  ('On the Road', 'Jack Kerouac', 'Fiction'),
  ('A Year in Provence', 'Peter Mayle', 'Narrative Non-Fiction'),
  ('A Year in Provence (second copy)', 'Peter Mayle', 'Narrative Non-Fiction'),
  ('The Inheritance of Loss', 'Kiran Desai', 'Fiction'),
  ('Three Men in a Boat', 'Jerome K. Jerome', 'Fiction'),
  ('The Sheltering Sky', 'Paul Bowles', 'Fiction'),
  ('The Sonnets', 'William Shakespeare', 'Literature & Reference'),
  ('A Midsummer Night''s Dream', 'William Shakespeare', 'Literature & Reference'),
  ('Quotations of John F. Kennedy', 'Applewood Books', 'Literature & Reference'),
  ('Eats, Shoots & Leaves', 'Lynne Truss', 'Literature & Reference'),
  ('The Elements of Eloquence', 'Mark Forsyth', 'Literature & Reference'),
  ('A Waiter in Paris', 'Edward Chisholm', 'Biography & Memoir'),
  ('The Road to Wigan Pier', 'George Orwell', 'Narrative Non-Fiction'),
  ('Storm of Steel', 'Ernst Jünger', 'Biography & Memoir'),
  ('Homage to Catalonia', 'George Orwell', 'Biography & Memoir'),
  ('The Razor''s Edge', 'W. Somerset Maugham', 'Fiction'),
  ('The Complete Works of William Shakespeare', 'William Shakespeare', 'Literature & Reference'),
  ('In Cold Blood', 'Truman Capote', 'Narrative Non-Fiction'),
  ('Seven Years in Tibet', 'Heinrich Harrer', 'Biography & Memoir'),
  ('Don Quixote', 'Miguel de Cervantes', 'Fiction'),
  ('Who Walk Alone', 'Perry Burgess', 'Biography & Memoir'),
  ('Antiquarian volume — title illegible', 'Unknown', 'Literature & Reference'),
  ('Flyfishing in Tasmania', 'Unknown', 'Australia'),
  ('Robin of Sherwood', 'Major Charles Gilson', 'Fiction'),
  ('The King''s English', 'Kingsley Amis', 'Literature & Reference'),
  ('Dreyer''s English', 'Benjamin Dreyer', 'Literature & Reference'),
  ('The Last of the Mohicans', 'James Fenimore Cooper', 'Fiction'),
  ('To Turn the Tide', 'John F. Kennedy', 'History'),
  ('Smiley''s People', 'John le Carré', 'Fiction'),
  ('Money', 'Martin Amis', 'Fiction'),
  ('The Master and Margarita', 'Mikhail Bulgakov', 'Fiction'),
  ('Mein Kampf', 'Adolf Hitler', 'History'),
  ('The Oxford English Dictionary (12 vols)', 'Oxford University Press', 'Literature & Reference'),
  ('Someone in the Attic', 'Andrea Mara', 'Fiction'),
  ('The Uncommon Reader', 'Alan Bennett', 'Fiction'),
  ('The Cambridge Book of Days', 'Rosemary Zanders', 'Literature & Reference'),
  ('Land Rover', 'Ben Fogle', 'Biography & Memoir'),
  ('The Times Quick Cryptic Crossword (Book 1)', 'The Times', 'Literature & Reference'),
  ('The Times Quick Cryptic Crossword (Book 2)', 'The Times', 'Literature & Reference'),
  ('The Second QI Book of General Ignorance', 'John Lloyd & John Mitchinson', 'Literature & Reference'),
  ('Kafka on the Shore', 'Haruki Murakami', 'Fiction'),
  ('Life of Pi', 'Yann Martel', 'Fiction'),
  ('Midnight in the Garden of Good and Evil', 'John Berendt', 'Narrative Non-Fiction'),
  ('Conversations with Friends', 'Sally Rooney', 'Fiction'),
  ('Trick Mirror', 'Jia Tolentino', 'Science & Ideas'),
  ('Run', 'Ann Patchett', 'Fiction'),
  ('City of Girls', 'Elizabeth Gilbert', 'Fiction'),
  ('Wolf Hall', 'Hilary Mantel', 'Fiction'),
  ('The Blind Assassin', 'Margaret Atwood', 'Fiction'),
  ('The Alchemist', 'Paulo Coelho', 'Fiction'),
  ('Brooklyn', 'Colm Tóibín', 'Fiction'),
  ('Big Little Lies', 'Liane Moriarty', 'Fiction'),
  ('Call Me By Your Name', 'André Aciman', 'Fiction'),
  ('The Curious Incident of the Dog in the Night-Time', 'Mark Haddon', 'Fiction'),
  ('The Bee Sting', 'Paul Murray', 'Fiction'),
  ('Fight Club', 'Chuck Palahniuk', 'Fiction'),
  ('A Gentleman in Moscow', 'Amor Towles', 'Fiction'),
  ('A Fine Balance', 'Rohinton Mistry', 'Fiction'),
  ('A Little Life', 'Hanya Yanagihara', 'Fiction'),
  ('People & Other Aggravations', 'Judith Viorst', 'Literature & Reference'),
  ('The Encyclopedia of Natural Medicine', 'Michael Murray & Joseph Pizzorno', 'Literature & Reference'),
  ('Normal People', 'Sally Rooney', 'Fiction'),
  ('The Fault in Our Stars', 'John Green', 'Fiction'),
  ('Prophet Song', 'Paul Lynch', 'Fiction'),
  ('The Body', 'Bill Bryson', 'Science & Ideas'),
  ('Down Under', 'Bill Bryson', 'Narrative Non-Fiction'),
  ('Notes from a Small Island', 'Bill Bryson', 'Narrative Non-Fiction'),
  ('The Mother Tongue', 'Bill Bryson', 'Literature & Reference'),
  ('At Home', 'Bill Bryson', 'Narrative Non-Fiction'),
  ('One Summer: America 1927', 'Bill Bryson', 'History');
